server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/order_command_db
spring.datasource.username=root
spring.datasource.password=Theanh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true