server:
  port: 8085

spring:
  application:
    name: account-service
  profiles:
    active: @spring.profiles.active@


management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: INFO
    web: INFO